"""
Minimal, hand-written type stub for the parts of `noiseprotocol` that
vault_tcp.py actually uses. The upstream package ships no py.typed marker,
so without this mypy treats every self.proto.* call as Any - silently
skipping type checking on exactly the crypto/handshake code that matters
most. Extend this file if vault_tcp.py starts using more of the API.
"""

from enum import Enum

class Keypair(Enum):
    STATIC = ...
    REMOTE_STATIC = ...
    EPHEMERAL = ...
    REMOTE_EPHEMERAL = ...

class _KeyPair:
    public_bytes: bytes

class _HandshakeState:
    rs: _KeyPair | None

class _NoiseProtocol:
    handshake_state: _HandshakeState

class NoiseConnection:
    handshake_finished: bool
    noise_protocol: _NoiseProtocol

    @classmethod
    def from_name(cls, name: bytes) -> NoiseConnection: ...
    def set_as_initiator(self) -> None: ...
    def set_as_responder(self) -> None: ...
    def set_keypair_from_private_bytes(self, keypair: Keypair, private_bytes: bytes) -> None: ...
    def set_keypair_from_public_bytes(self, keypair: Keypair, public_bytes: bytes) -> None: ...
    def start_handshake(self) -> None: ...
    def write_message(self, payload: bytes = ...) -> bytes: ...
    def read_message(self, data: bytes) -> bytes: ...
    def encrypt(self, plaintext: bytes) -> bytes: ...
    def decrypt(self, ciphertext: bytes) -> bytes: ...
